apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: {{ .Release.Namespace }}
  labels:
    app: keycloak
spec:
  serviceName: keycloak-discovery
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: {{ print .Values.image.image ":" .Values.image.tag }}
          args: ["start"]
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valuesFrom:
                secretKeyRef:
                  name: {{ .Values.config.secret.name }}
                  key: {{ .Values.config.secret.usernameKey }}
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valuesFrom:
                secretKeyRef:
                  name: {{ .Values.config.secret.name }}
                  key: {{ .Values.config.secret.passwordKey }}
            - name: KC_PROXY_HEADERS
              value: {{ .Values.config.proxyHeaders }}
            - name: KC_HTTP_ENABLED
              value: {{ .Values.config.httpEnabled | quote }}
            - name: KC_HOSTNAME
              value: {{ .Values.config.hostname }}
            - name: KC_HEALTH_ENABLED
              value: {{ .Values.config.healthcheck | quote }}
            - name: 'KC_CACHE'
              value: {{ .Values.config.cache }}
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KC_CACHE_EMBEDDED_NETWORK_BIND_ADDRESS
              value: '$(POD_IP)'
            - name: 'KC_DB_URL_DATABASE'
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secret.name }}
                  key: {{ .Values.database.secret.databaseKey }} 
            - name: 'KC_DB_URL_HOST'
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secret.name }}
                  key: {{ .Values.database.secret.hostKey }} 
            - name: 'KC_DB'
              value: {{ .Values.database.type }}
            - name: 'KC_DB_PASSWORD'
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secret.name }}
                  key: {{ .Values.database.secret.passwordKey }}
            - name: 'KC_DB_USERNAME'
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secret.name }}
                  key: {{ .Values.database.secret.usernameKey }} 
          ports:
            - name: http
              containerPort: 8080
            - name: jgroups
              containerPort: 7800
            - name: jgroups-fd
              containerPort: 57800
          startupProbe:
            httpGet:
              path: /health/started
              port: 9000
            periodSeconds: 1
            failureThreshold: 600              
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
            periodSeconds: 10
            failureThreshold: 3              
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9000
            periodSeconds: 10
            failureThreshold: 3
{{ if .Values.resources }}
{{ .Values.resources | indent 10 }}
{{ end }}